terrestris/BasiGX

- .travis.yml
> Add very basic travis config for CI

- Readme.md
> Add coveralls badge

- src/view/component/Map.js
- test/spec/plugin/Hover.test.js
This also includes a slight change to the `src/view/component/Map.js`. Please review.
> Add some basic tests for Hover plugin

- examples/csvimport/index.html
fixed the example by replacing local resources with online ones
> replaced broken local resources

- src/plugin/WfsCluster.js
> removed hardcoded url in cluster source

- src/plugin/WfsCluster.js
- test/spec/plugin/WfsCluster.test.js
- test/spec/util/Animate.test.js
- test/spec/util/Application.test.js
- test/spec/util/ConfigParser.test.js
I added some more tests for the BasiGX package. Configparser is still rough but should be ok since it will get reworked soon i believe
> added tests for wfscluster, animate, application and configparser

- src/util/Animate.js
Can be used to e.g. translate features from a clustered position to their original position.
> Added new Animate util method to translate features

- src/view/panel/LayerSetChooser.js
> made template in Layersetchooser configurable

- src/view/panel/MobileWindow.js
This panel can be used to imitate a window like component. It has a header which can have a title and also serves a closable "X" button to close the panel
> Added a window-like panel for modern applications

- src/view/container/WfsSearch.js
removed cleanuploop as its not necessary and has a huge impact on performance
> Removed useless and performance breaking code

- src/plugin/Hover.js
This introduces two new configuration options for the hover plugin:
* `selectMulti`, and
* `selectEventOrigin`
With `selectMulti` you can control whether the select interaction may ever
possibly select more than one feature from the hover layer. The default is
`true` for backwards compatibillity.
With `selectEventOrigin` you can control if you want the origin of the
click event firing to be the collection of the select interaction (`add`
event, also the default for historical reasons) or the interaction itself
(its `select` event).
This PR shouldn't introduce any regressions, as the configs are fully optional.
Please review.
> Make source & behaviour of selection configurable

- package.json
> Update coveralls to v2.11.6

- package.json
> Update eslint to v1.10.3

- package.json
> Update istanbul to v0.4.1

- package.json
> Update mocha to v2.3.4

- test/spec/plugin/Hover.test.js
Title says it all. Please review.
> Add more tests for selectEventOrigin config

- src/util/ConfigParser.js
> Fix indentation

- src/util/CSRF.js
Will get more and more usable in the future when SHOGun2 gets spread..
> Added CSRF header util

- src/util/CSRF.js
follow up for already merged PR https://github.com/terrestris/BasiGX/pull/44
> Added header and documentation to CSRF util

- test/index.html
- test/raf.polyfill.js
Current tests fail on master of ol3 as the phantomjs aint capable of using the `requestAnimationFrame` function. This PR fixes this by adding an appropriate polyfill for phantomjs
> Fix the tests by using polyfill for phantomjs

- src/util/Object.js
- test/load-tests.js
- test/spec/util/Object.test.js
Added new util to work with Objects. Currently supports getting a specific value from a nested Object
> Added Object util

- src/view/panel/LegendTree.js
Fixes a minor coloring issue in IE9
> Added fallback for IE9 in treeColor

- src/util/MsgBox.js
> Introducing a msgbox util

- src/view/panel/GraphicPool.js
Moved Class to correct folder, added msg on upload failure
> Minor Cleanups on GraphicPool

- src/util/Layer.js
- test/spec/util/Layer.test.js
The new method `getLayersBy` makes it possible to get layers by specific key - value combination
> Introducing new layer util method getLayersBy

- src/view/form/CoordinateTransform.js
See original PR  #72.
Closes #72.
> Enhance the reusablity of the CoordinateTransform form

- src/view/form/Print.js
- Introduces the missing functions for NorthArrow and ScaleBar.
- Allow printattribute stringfields to be empty.
> Printconfig

- src/util/Color.js
- src/view/container/RedlineStyler.js
- src/view/container/Redlining.js
- test/index.html
- test/load-tests.js
- test/spec/view/container/Redlining.test.js
This PR adds some stateful behaviour to Redlining with the help of `getState` and `setState` methods
> Added stateful behaviour to Redlining Components

- src/view/form/AddWms.js
This includes:
* a configuration option to also show checkboxes for sublayers
* configurable check/uncheck all layers checkboxes buttons
* configurabl initial state of a layer checkbox
* loadmask while fetching data, parsing it and creating the new UI
* automagically configuring UI disabled state (interactions with
the list of layers)
* some display of layers in two columns
* scrollable layers-list
* internal restructuring (named functions instead of anonymous ones)
* some inline TODO comments for future tasks
Please review.
> Several enhancements for WMS GetCapabilities form

- src/view/container/Redlining.js
> Made the postit image source configurable

- src/view/form/CoordinateTransform.js
> Hiding the coordinate transform vector layer as default

- src/view/container/Redlining.js
This adds an event that fires everytime a feature is added, deleted, moved or modified.
> Adds "redliningchanged"-event to redlingin container.

- src/view/button/Hsi.js
Merging without review due to minor
> Fixed a Typo for Component Query

- src/plugin/Hover.js
After adding the stroke style we are now able to hover correctly on linestrings.
Hovered feature will now be highlighted and click on feature will be handled correctly
> Enabled hovering for LineStrings

- src/view/button/ZoomIn.js
- src/view/button/ZoomOut.js
- src/view/button/ZoomToExtent.js
We missed a `getMap()` call here on the component.
> Fixing the ZoomButtons

- src/util/Animate.js
- src/view/container/Redlining.js
This PR fixes several minor redlining issues.
The usability has improved, as the interactions now make use of a hovereffect, indicating which feature is currently selected to modify / delete etc.
The text of postits is now editable with the modify tool.
The util.Animate has been made compatible for changes in ol3 later than v3.15
> Several redlining enhancements

- src/view/form/Print.js
This MR provides two fixes for `BasiGX.view.form.Print` class:
1. `northArrow` attribute definition was unusable due to wrong object assignaiton
2. Method `renderAllClientInfos` will be called much more rarely now since a `moveend` event of the map will be used instead of too global `changeproperty` event of the ol.View. Additionally this event will be unregistried again after print window was closed.
> Print form fixes

- test/index.html
> Trying to fix travis

- src/view/container/Redlining.js
This change displays a configurable message when the maxLength of the text for postits has been exceeded. The user can then continue or edit the text
> Warning in case of text too long for postits

- src/view/container/Redlining.js
This enables clean usage of screen sharing when using postits, as the style of a postit has to be set before it gets pushed to the redlinefFeatures collection. Also enhanced the modifyPostit function to reflect latest changes on maxLength
> Making the postit work better with screen share

- test/index.html
- test/resources/locale/app-locale-de.json
- test/spec/view/combo/Language.test.js
- test/spec/view/combo/ScaleCombo.test.js
This changes minors of the testsuite, to make it more stable.
This should be reviewed/merged before  #115 and #116 are in.
> Minor test adjustments

- src/util/Layer.js
- src/view/button/Measure.js
- test/spec/view/button/Measure.test.js
This PR enables the `measureType` angle to measure angles.
Please review.
Hey @buehner @annarieger would be nice if you could have a look.
/cc @weskamm You might be interested as well.
> Allow measurement of line angles

- .eslintrc
- src/plugin/Hover.js
Here you'll find some enhancements regarding the hover plugin class:
* Prettify indenting (no functional enhancement...)
* Introduce `dynamicHoverColor` config. If set to true, the hovered feature color will be determined by the currently hovered pixel color value.
* Add hoverTemplate strings, that can be used to create more complex feature info popup contents, e.g. to have a combination of different feature properiers. See new method `getHoverTextFromTemplate()`.
> Hover plugin enhancements

- src/view/container/MultiSearchSettings.js
- src/view/form/field/MultiSearchCombo.js
- src/view/grid/MultiSearchGazetteerGrid.js
- src/view/grid/MultiSearchWFSSearchGrid.js
> introducing multisearch - rebased

- src/view/panel/LegendTree.js
> Make custom handling for initially collapsed panel version dependent

- .gitignore
- .sencha/package/Boot.js
- .sencha/package/Microloader.js
- .sencha/package/build-impl.xml
- .sencha/package/codegen.json
- .sencha/package/init-impl.xml
- .sencha/package/sass-impl.xml
- .sencha/package/sencha.cfg
- .sencha/package/slice-impl.xml
- ci/create-sencha-environment.sh
- ci/create-sencha-package.sh
- ci/shared.sh
- ci/update-gh-pages.sh
- package.json
This PR suggests to upgrade to using ext 6.2.0 and the newest sencha cmd (v6.2.1.29).
Please review.
> Build using latest sencha / ExtJS during CI

- Readme.md
> Align badges in README

- Readme.md
> Link to API docs in README

- src/view/button/ZoomToExtent.js
Title says it all; this allows people to also reset the rotation when the zoom to the start extent.
I also added docs, some `TODO` and harmonized the look of the source code.
Please review.
> Also reset rotation when zooming to an extent

- src/view/form/AddWms.js
> Update the BasiGX Add WMS Dialog - combobox for urls REOPENED

- src/view/form/AddWms.js
> Update the BasiGX Add WMS Dialog - fix default values

- src/util/Geometry.js
This adds a small geometry util. Maybe if you don't want to include jsts for just one operation.
For know it only contains a static equals method to compare to ol.geometries.
It could be extended with further functions.
> Adds Geometry Util.

- src/util/Animate.js
This change adds support for animated LineStrings and Polygons.
Support for older version of OpenLayers (below 3.15) may be added in upcoming PR.
Please review
> Supporting LineStrings and Polygons in flashFeature method

- src/view/button/Measure.js
- Reenable the code that fixes the bug.
- Minor formatting.
Plz review @terrestris/devs
> Fixes doubled labels at the end of a drawn line.

- src/view/combo/Language.js
Title says it all, please review.
Before:
After:
> Fix top-level API docs of language combo

- src/util/Accessibility.js
- test/spec/util/Accessibility.test.js
The title says it all.
Please review.
> Add method to get <html>-tags lang-attribute

- src/view/panel/TtfGlyphInspector.js
Mainly the `@class` had a wrong value.
Please review
> Correct the docs of TtfGlyphInspector

- src/util/SldOpenlayersConverter.js
This SLD <-> OpenLayers style converter can be useful in many projects.
> Extracted sld <-> ol style converter

- src/view/container/WfsSearch.js
This introduces some improvments:
- configurable columns for the searchgrid
- showSearchResults receives the featureCollection not features. Usefull for overrides.
This should be merged prior to #188 
@terrestris/devs plz review
> WfsSearch improvements

- src/view/form/Print.js
> Keep transformed feature when moving the map

- src/util/Caching.js
- test/load-tests.js
- test/spec/util/Caching.test.js
These methods may be helpful if you are using a GeoWebCache (integrated in a GeoServer).
I'll try to add some tests tomorrow.
> Caching util methods

- package-lock.json
This updates our `package-lockfile.json` to a newer state. In the future, this will happen automatically, once #211 is merged.
Please review.
> Update package-lock.json for current package.json

- src/plugin/Hover.js
This enhances the popzup positioning, so that the popup is usually show, even when hovering at the edges or cornes of the map component.
Please review.
> Better ol.Overlay positioning

- src/plugin/Hover.js
Title says it all (from https://github.com/terrestris/BasiGX/pull/217#discussion_r137242184, thanks @annarieger), no formal review needed.
Will merge when green
> Fix typo in API docs

- examples/animation/animate.js
- examples/animation/index.html
- src/util/Animate.js
Added new animations `Follow Vertices` and `Follow Segments`
> New animations!

- src/view/form/Print.js
> Translate scale bar & north arrow

- src/view/button/AddWms.js
- src/view/button/CoordinateTransform.js
- src/view/button/Permalink.js
- src/view/container/RedlineStyler.js
- src/view/container/SLDStyler.js
- src/view/form/field/MultiSearchCombo.js
- src/view/grid/GazetteerGrid.js
This PR suggests to use `constrain: true` when we create windows.
Please review.
> Constrain windows we create

- package-lock.json
- package.json
> Update coveralls to v3.0.0

- src/util/Merge.js
- src/view/button/MergeSelection.js
- src/view/grid/FeatureGrid.js
- src/view/window/MergeWindow.js
This adds a button and some utils to merge the features of one layer into another. After clicking the button the user can map attributes of the source layer to attributes of the target layer and select which attributes to add to the target layer's schema.
> Merge layers

- src/util/Filter.js
- src/util/SLD.js
- src/util/WFS.js
This PR adds some util methods to work with WFS and OGC Filters.
Please review
> Added WFS and OGC Filter utils

- src/view/button/MergeSelection.js
Changed parameter type to ol.layer.Vector
@weskamm please review
> Changed parameter type in merge selection button config

- src/util/ConfigParser.js
This fixes a warning people get in some applications when parsing the app context.
> implemented an array variant of string to array conversion

- src/util/WFS.js
Allows usage of maxFeatures parameter, only appends spatial filter if extent was given
> Enhancing the WFS util

- src/view/window/MergeWindow.js
> Minor layout enhancements for MergeWindow

- src/util/Merge.js
- src/view/window/MergeWindow.js
> Fixed filtering of mapped attributes in merge window

- src/util/Digitize.js
- src/view/button/DigitizeCopyObject.js
- src/view/button/DigitizeDeleteObject.js
- src/view/button/DigitizeModifyObject.js
- src/view/button/DigitizeMoveObject.js
- src/view/button/DigitizeOpenStyler.js
- src/view/button/DigitizePostit.js
- src/view/container/Redlining.js
This moves the single buttons like modify or delete object and their logic to their own classes.
> Refactor redlining container

- src/util/Digitize.js
- src/view/button/DigitizeCopyObject.js
- src/view/button/DigitizeDeleteObject.js
- src/view/button/DigitizeLine.js
- src/view/button/DigitizeModifyObject.js
- src/view/button/DigitizeMoveObject.js
- src/view/button/DigitizePoint.js
- src/view/button/DigitizePolygon.js
- src/view/button/DigitizePostit.js
> Fixup redlining tools

- test/.eslintrc
- test/spec/util/Application.test.js
- test/spec/util/Layer.test.js
- test/spec/view/container/Redlining.test.js
- test/spec/view/list/FocusableTreeItem.test.js
- test/spec/view/panel/Accessible.test.js
- test/spec/view/window/Accessible.test.js
> Fixed randomly failing tests

- src/view/button/DigitizeLine.js
- src/view/button/DigitizePoint.js
- src/view/button/DigitizePolygon.js
> Allow digitizing of multi geometries via config option

- src/view/grid/FeatureGrid.js
> Fixed ie11 incompatibility

- src/view/grid/FeatureGrid.js
> Fix unByKey call to use static function

- package-lock.json
- package.json
> Greenkeeper/sinon 4.4.2

- src/util/SLD.js
- src/view/container/SLDStyler.js
- test/spec/util/SLD.test.js
This adds support for styling TextSymbolizers in the SLD Styler.
> Added TextSymbolizer handling in SLD util and styler

- src/util/WFS.js
- src/view/container/SLDStyler.js
- test/load-tests.js
- test/spec/util/WFS.test.js
@weskamm @terrestris/devs please review
> Get smarter when parsing cql filters using regexp

- src/view/form/AddWms.js
> Use transparent: true param when adding wms

- test/index.html
Replaces outdated links for `ogc-schema`/`w3c-schema` sources.
> Fix failing build

- package-lock.json
- package.json
> Greenkeeper/sinon 5.0.10

- src/plugin/Hover.js
> Configurable FEATURE_COUNT in GetFeatureInfo requests

- package-lock.json
- package.json
> Greenkeeper/eslint 5.0.1

- src/plugin/Hover.js
This adds a `maxHeight` config to the hover plugin.
@weskamm Please review.
> Add max height config for hover overlays

- src/view/form/Print.js
> Reset print extent and rotation after selecting a layout

- src/view/panel/CoordinateMousePositionPanel.js
Title says it all, please review.
> Do not update coord textfields while they have focus

- src/util/Layer.js
- test/spec/util/Layer.test.js
> Add getLayersBy util

- test/load-tests.js
- test/spec/view/button/History.test.js
> Add basic unit tests for HistoryButton

- .eslintrc
- src/view/window/FileUploadWindow.js
This adds a simple file upload window which reads in the file as text to provide it to a callback.
> Adds a file upload window

- src/plugin/Hover.js
- src/util/Layer.js
- src/util/Object.js
- src/util/Projection.js
- src/util/SldOpenlayersConverter.js
- src/util/Url.js
- src/util/WFS.js
- src/ux/RowExpanderWithComponents.js
- src/view/MapLoadingStatusBar.js
- src/view/container/Redlining.js
- src/view/container/SLDStyler.js
- src/view/grid/MultiSearchWFSSearchGrid.js
- src/view/panel/CoordinateMousePositionPanel.js
- src/view/panel/LegendTree.js
- test/spec/util/Layer.test.js
> Fixes all remaining linting warnings

- src/util/WFS.js
- test/spec/util/WFS.test.js
Title says it all, please review.
> Add several tests for the WFS util

- package-lock.json
- package.json
Title says it all, please review.
>  Update eslint to v5.10.0

- .gitignore
- package-lock.json
- package.json
- test/test-helper-functions.js
See the commit messages for the details.
Please review.
> Various minor cleanups

- karma-conf.common.js
- src/view/form/AddWms.js
- test/spec/view/form/AddWms.test.js
This adds a bunch of tests. Please review.
> Add some more tests

- src/ol3/extension/TransformInteraction.js
- src/plugin/Hover.js
- src/plugin/WfsCluster.js
- src/util/Animate.js
- src/util/ConfigParser.js
- src/util/Controller.js
- src/util/Layer.js
- src/view/button/Measure.js
- src/view/button/ZoomIn.js
- src/view/button/ZoomOut.js
- src/view/button/ZoomToExtent.js
- src/view/component/Map.js
- src/view/container/NominatimSearch.js
- src/view/container/OverpassSearch.js
- src/view/container/RedlineStyler.js
- src/view/container/Redlining.js
- src/view/container/WfsSearch.js
- src/view/form/AddWms.js
- src/view/grid/GazetteerGrid.js
- src/view/grid/MultiSearchGazetteerGrid.js
Title says it all. Please review.
> Fix spelling and wording in comments

- src/util/Layer.js
Follow-up of #381, adressing remarks by @chrismayer.
Please review.
> Fix spelling

- src/view/container/SLDStyler.js
Follow up / Bugfix to #385 
- remebers text symbolizer checkbox state
@terrestris/devs Pls review
> Set initial point symbolizer checkbox value

- src/util/Download.js
> Fix json download

- sass/etc/all.scss
- src/view/combo/ScaleCombo.js
- src/view/grid/FeatureGrid.js
- src/view/window/PreviewWindow.js
Adds a layer preview window:
* shows the legend, if any
* can zoom to the data extent, if any
* has zoom controls
* has a scale combo
* shows a feature info window when clicking on a feature
> Add a layer preview window

- sass/src/view/panel/LegendTree.scss
Fixes vanishing of large legends in firefox.
> Fix legend tree css for firefox

- src/view/window/FileUploadWindow.js
> Add option to hide fakepath part

- karma-conf.common.js
- package-lock.json
- src/view/form/AddWms.js
- test/resources/ows/service-1.1.1.xml
- test/resources/ows/service-1.3.0.xml
- test/spec/view/form/AddWms.test.js
This adds a couple of tests for the AddWMS form. Please review.
> Add several tests for AddWMS behaviour

- src/view/button/AddWms.js
- src/view/button/CoordinateTransform.js
- test/spec/view/button/AddWms.test.js
- test/spec/view/button/Base.test.js
- test/spec/view/button/CoordinateTransform.test.js
- test/spec/view/form/CoordinateTransform.test.js
- test/spec/view/form/CsvImport.test.js
- test/spec/view/form/Permalink.test.js
- test/spec/view/form/Print.test.js
This adds a couple of basic tests and also cleans up better after we destroy instances.
> Add some basic tests & cleanup on destroy

- src/util/Geometry.js
- src/util/GeometryOperations.js
- src/util/MouseCoordinates.js
- src/util/Object.js
- src/util/WPS.js
- src/view/combo/ScaleCombo.js
- src/view/form/CoordinateTransform.js
- test/spec/util/Date.test.js
- test/spec/util/Geometry.test.js
- test/spec/util/WFS.test.js
- test/spec/view/button/AddWms.test.js
- test/spec/view/button/CoordinateTransform.test.js
- test/spec/view/button/History.test.js
- test/spec/view/button/ZoomOut.test.js
- test/spec/view/form/CsvImport.test.js
- test/spec/view/panel/FontSymbolPool.test.js
- test/spec/view/panel/GraphicPool.test.js
- test/spec/view/view/GraphicPool.test.js
- test/test-helper-functions.js
Adds a geometry comparison that compares with a delta. Also fixes a lot of linting errors (unsure why travis doesn't find them, they fail my tests locally).
> Add proper geometry comparison

- ci/update-gh-pages.sh
- package.json
> Add minified version on github pages

- src/view/grid/FeatureGrid.js
Title says it all. @terrestris/devs Please review.
> Lock and disable the zoom column

- src/util/WPS.js
We missed this part when util.JSONIX was introduced
> Fix faulty reference to util

- package.json
- src/ux/RowExpanderWithComponents.js
- src/view/button/DigitizeDeleteObject.js
- src/view/button/DigitizeModifyObject.js
- src/view/button/DigitizeMoveObject.js
- src/view/button/DigitizePostit.js
> Slightly enhanced docs

- src/plugin/Hover.js
@terrestris/devs 	Please review.
> Enables autopositioning of items partially outside the map

- karma-conf.common.js
- package-lock.json
- package.json
Trying to fix karma issues with browser env variable
> Fix test failures

- package-lock.json
- package.json
> Greenkeeper/rimraf 3.0.0

- src/util/Jsonix.js
> Enhance documentation for using Jsonix / JsonixUtil

- package-lock.json
- package.json
> Greenkeeper/karma coverage 2.0.1

- package-lock.json
- package.json
> Greenkeeper/eslint 6.7.1

- src/view/component/Map.js
- src/view/form/AddWms.js
> Add queryable flag when adding WMS

- src/view/button/CSW.js
Same problem that we had here: https://github.com/terrestris/BasiGX/pull/513
This PR solves the problem
> Fix CSW window bug

- sass/etc/all.scss
- src/view/window/PreviewWindow.js
- move the show legend button from the header to the map
- change icon to _fa-info_
- force legend labels (without labels it makes no sense)
- fix of button tooltips
> Fix Layer Preview Window: legend button, tooltips

- src/view/panel/GraphicPool.js
- src/view/view/GraphicPool.js
- makes window size configurable for the graphicpool
- adds _overItemCls_ config to define a hover-css class for each graphic-item in the pool
> Fix of hover-effect for graphicpool

- Readme.md
- package-lock.json
- package.json
* Introduced `engines` block to `package.json`
* Sets minimum required node version to `>=10`
* Updated `np` package to `v6.1.0` (needs node >10)
> Set minimum required node version to >=10

- src/plugin/Hover.js
15 pixels are not enough padding when you're hovering to the right and get a popup with a scrollbar.
> Increase padding when hovering

- src/util/StringTemplate.js
- src/util/WPS.js
- src/view/button/Base.js
- src/view/form/AddWms.js
- src/view/form/CSW.js
- src/view/form/field/MultiSearchCombo.js
- src/view/grid/MultiSearchGazetteerGrid.js
- test/spec/plugin/Hover.test.js
- test/spec/util/StringTemplate.test.js
- test/spec/view/button/AddWms.test.js
- test/spec/view/button/CoordinateTransform.test.js
Title says it all. @terrestris/devs Please review.
> Fix extraction of layers when no bbox is available

- src/view/form/AddWms.js
Previously only the first level of sublayers was collected. With this PR all sublayers are considered, no matter how deeply nested.
> Collect all sub layers in add wms form

- src/store/GazetteerSearch.js
- src/view/container/NominatimSearch.js
- src/view/grid/MultiSearchGazetteerGrid.js
Due to CORS issues with nominatim.openstreetmap.org.
> Change nominatim service to nominatim.terrestris.de

- src/view/grid/MultiSearchWFSSearchGrid.js
Title says it all. @terrestris/devs Please review.
> Fix WFS search wrt non standard namespace prefixes

- package-lock.json
- package.json
> Update puppeteer to v4.0.1

- src/view/window/PreviewWindow.js
> Fix legend window title

- src/view/form/Print.js
Add config flag to be able to use standard ajax requests instead of jsonp.
> Add jsonp config flag

- src/util/Layer.js
This PR suggest to move the function check outside of the loop. 
Please review.
> Function check out of loop

- src/util/Layer.js
This PR suggest to harmonize return values. 
Please review.
> fix return value

- src/view/grid/MultiSearchWFSSearchGrid.js
@terrestris/devs please note.
cf. https://github.com/terrestris/BasiGX/pull/626#pullrequestreview-567377873
> Minor: Improve check for search result click

- src/view/grid/MultiSearchWFSSearchGrid.js
Always search with lower case search terms, also always specify the output projection.
> Fix multisearch

- package-lock.json
This updates the `package-lock.json` file to fix several low severity vulnerabilities.
Please review.
> Update dependencies and fix 6 low severity vulnerabilities

- src/view/grid/MultiSearchWFSSearchGrid.js
See title. @terrestris/devs Please review.
> Compare lower case when displaying results dynamically

- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-master.yml
- karma-conf.common.js
- package-lock.json
- package.json
> Use fixed geoext version 3.4 for tests

- src/util/Layer.js
- src/view/button/Geolocation.js
This adds a simple geolocation tool that is toggable.
> add geolocation button

- src/view/button/ZoomIn.js
- src/view/button/ZoomOut.js
> Fix zoomin/out buttons for the modern toolkit

- src/olExt/TransformInteraction.js
Makes the transform interaction compatible with ol6.
> Fix transform interaction

- src/view/grid/FeatureGrid.js
Add the possibility to configure locking and the header on the underlying grid.
> Configure feature grid

- src/view/form/Print.js
> Allow configuration of aspect ratio behaviour

- src/plugin/HoverClick.js
See in title, required due to the update to ol version 6.
> Pass scope via bind

- src/view/grid/FeatureGrid.js
This sets the highlight style for all geometry types.
> Fix highlight style for all geometry types

- src/olExt/TransformInteraction.js
Makes sure aspect ratio is also kept when using the side handles.
> Properly keep aspect radio if configured

- src/view/grid/FeatureGrid.js
> Adds configuration for enabling filtering on featureGrid

- package.json
- src/util/WFST.js
- src/view/grid/FeatureGrid.js
Title says it all...
WFST Util based on work of @hwbllmnn.
> Introduce WFS-T on Feature Grid

- src/view/grid/FeatureGrid.js
This dis-/enables the insert buttons and sets their geometry to single/multi, depending on the listed `geometryTypes`.
> handle different geometry types

- src/view/grid/FeatureGrid.js
This allows configuring, if column renaming/deletion should be enabled
> Add configuring column renaming/deletion

- src/view/grid/FeatureGrid.js
This adds a reminder text to the feature grid top bar, which will be shown in a configurable delay triggered after the first edit.
> Add delayed save reminder text

- src/view/grid/FeatureGrid.js
- src/view/panel/LegendTree.js
added 100ms timeout to update map size when:
- opening or closing feature grid
- when expanding and collapsing legend tree
> Update map size on expanding/collapsing legend tree and opening/closing feature grid

- src/view/grid/FeatureGrid.js
- Added enableRefreshButton parameter to FeatureGrid 
- Adapted code to correctly show the reload button is this option is set to true
> FeatureGrid: add parameter to always show reload button

- src/view/grid/FeatureGrid.js
- src/view/panel/LegendTree.js
This fixes several linter warnings and errors.
> Lint fixes

- src/util/WFS.js
The previous code only supported TileWMS as layer source type, but did not support ImageWMS.
This will fix it.
> Also support ImageWMS when filtering

- src/util/Projection.js
- src/view/panel/CoordinateMousePositionPanel.js
Fix for #693 as http requests no longer work, always use https.
> Ensure HTTPS for epsg.io requests

- .gitignore
- src/view/form/CoordinateTransform.js
> Fix jslint

- src/view/grid/FeatureGrid.js
> feat: add zoom padding

- src/view/grid/FeatureGrid.js
same as https://github.com/terrestris/BasiGX/pull/735 just for branch `v3.x`
> add maxZoom to FeatureGrid

- src/view/grid/FeatureGrid.js
This disables editing features when no `idField` is provided on the layer the features are based on. Without this property, we do not now the name of the primary key column and thereby cannot properly update items via WFS-T.
Additionally, newly added features will also be tracked in a dedicated array in order to increase the robustness in comparison to only checking for the existence of a value in the idField column.
> fix(featuregrid): disable editing when no idField provided

- src/view/grid/FeatureGrid.js
> feat(featuregrid): add option to use number filter on numeric columns

- package-lock.json
- package.json
- src/view/MapLoadingStatusBar.js
This updates geoext and ol to version 8 and GeoExt to version 6.
> Upgrade to OpenLayers 8
