terrestris/BasiGX

ci/update-gh-pages.sh

Use the `-s` option to suppress the diff when getting author email and name.

Don't print diff when getting author email

---

ci/update-gh-pages.sh

On the gh-pages branch, we publish the locally created package BasiGX
which itself depends on the GeoExt package. Since in order to create
the BasiGX package, we had to add the GeoExt package, our local catalog
(`catalog.json` in the repo folder) also contains the description of
the GeoExt package.
When someone now tries to use the BasiGX package, that catalog is
queried. Since it also contains a reference to GeoExt (we simply
copied it over), the sencha cmd tries to resolve any GeoExt
dependencies from the BasiGX folder.
This commit ensures that we also publish the GeoExt package to the
BasiGX repo. In the future we may want to change the way we advertize
our catalog. See the TODO in the `update-gh-pages.sh`-file.

Publish the GeoExt-pkg, it's advertized in catalog

---

package.json

This removes a warning from npm:
```
npm WARN package.json BasiGX@1.0.0 license should be a valid SPDX license expression
```

Use a valid SPDX compatible version

---

src/view/container/OverpassSearch.js

Added the tagfinder API to the search, effectively reducing the search waiting time due to more concrete queries against overpass API. The user now gets a list of available tags with description for his searchterms, Overpass query gets executed with the selected offical osm tag after the user has selected one.

Added tagfinder to overpass search; several optimizations

---

src/view/form/AddWms.js

This fixes breaking of the component when capabilities return a layer without style information

Fixed problem on detecting wms-layer-styles in capabilities

---

src/view/button/AddWms.js
src/view/button/CoordinateTransform.js
src/view/button/Help.js
src/view/button/Hsi.js
src/view/button/Measure.js
src/view/button/Permalink.js
src/view/button/ToggleLegend.js
src/view/button/ZoomIn.js
src/view/button/ZoomOut.js
src/view/button/ZoomToExtent.js

This PR changes all current buttons to extend from `Ext.Button` instead of `Ext.button.Button`.
This way they are compatible with the classic and modern toolkit.
There are still buttons which cannot be used in the modern toolkit (Permalink, AddWms and CoordinateTransform), because they rely on classic components like windows.
Other changes involved are the usage of the constructor and moving the button handlers to the config object. 
The tooltip binding had to be taken special care of because the "modern" buttons dont support the `setToolTip` method.

Made the buttons usable for modern client

---

src/view/button/AddWms.js
src/view/button/CoordinateTransform.js
src/view/button/Help.js
src/view/button/Hsi.js
src/view/button/Measure.js
src/view/button/Permalink.js
src/view/button/ToggleLegend.js
src/view/button/ZoomIn.js
src/view/button/ZoomOut.js
src/view/button/ZoomToExtent.js
src/view/form/AddWms.js
src/view/form/CoordinateTransform.js
src/view/form/Permalink.js
src/view/form/Print.js
src/view/panel/LayerSetChooser.js
src/view/panel/LegendTree.js
src/view/panel/MapContainer.js
src/view/panel/Menu.js

Requires of `Ext.app.ViewModel` have been added to enable production builds on modern toolkits

Added missing viewModel requires

---

src/view/form/Print.js

This PR suggest that the print-combos for `apps`, `formats` and `layouts` are sorted alphabetically in ascending order.
I decided against configurabillity, since I cannot imagine a case where we want to have descending order.
The methods used to sort are diffenrent, as `apps` and `formats` are plain arrays, while `layouts()` actually gives us a store. The store can be soreted against any field of `GeoExt.data.model.print.Layout`, useful in our case s the name.
Please review and merge at your own will.

Sort apps, formats and layouts alphabetically

---

src/view/form/Print.js

This PR suggests adding the events `beforeattributefieldsadd` and `attributefieldsadd`, so that subclasses have a chance to alter the generated form, e.g. by hiding fields (or not adding them at all) or setting values.
Please review and merge at will.

Fire events while adding attributefields

---

src/plugin/Hover.js
src/util/ConfigParser.js
test/spec/plugin/Hover.test.js
test/spec/util/ConfigParser.test.js

This makes it easier for applications to determine the fields
which are used to controll hovering. If, for example you want
to disable hovering of a layer temporarily, you can now just
determine the correct property, and then set the value for it
to `false`.
This commit also adds basic tests that document the behaviour.
Once this is merged, we cannot 100% guarantee, that `hoverfield`
and `hoverable` properties exist on our layer instances.
Applications should now use the static fields from the
hoverplugin.
If an application has the need for different fields for hovering
the plugin class can be extended and the statics can be reassigned
to match the new environment. See the tests for an example of
this.

Read layer properties for hovering from fields

---

src/plugin/Hover.js
test/spec/util/ConfigParser.test.js

CamelCase usage of this property is the better choice as its already used in several backend-models in our applications. I tried an override first as we often extend the Hover class, but that leads to a lot of code and problems because of the early stage when the configparser handles this field. So maybe its easier to just change this property.
@marcjansen: Please check if this gets you in trouble :-)

Change default of LAYER_HOVERFIELD_PROPERTY_NAME

---

src/view/form/CoordinateTransform.js

Changed the detection of coordinates in events as `ol.MapBrowserPointerEvent` is not available in production builds of ol3

Fixed coordinatetransform for ol-production builds

---

src/util/ConfigParser.js

Like the title says, i removed the invalid mapping from startbbox to (restricted) extent.
Use center and zoom to set your maps initial start appearance

Removed the incorrect mapping from startbbox to restricted extent

---

src/util/ConfigParser.js

This fixes the ordering of layers that are contained in folders when using SHOGun 1 as backend serving the application context

Fixed layerorder while parsing shogun context

---

src/view/form/Print.js

MapFish-Print 3.4. supports default values for attributes
so we use it.

Use attributes default values from print-servlet

---

src/util/Animate.js

This PR fixes the issue in the `moveFeature` as described here: https://github.com/terrestris/BasiGX/issues/35
Util now can handle Points, LineStrings and Polygons

Fixed until.Animate.moveFeature

---

ci/update-gh-pages.sh

This skips the build of jsduck cause it crashes the and forfeit the merge into the jsduck branch.

Fix autodeployment of BasiGX

---

src/util/Animate.js

This PR refactors the moveFeature method. It is now able to handle different geometry types, has been tested with points, linestrings and polygons. We do now execute a `doneFunction` when the animation has finished.
Pixels are used for the feature displacement, the translate respects the current views resolution

rewrite of movefeature method

---

src/util/ConfigParser.js

This PR fixes an issue with SHOGun 1 appContext: 
Folders that contain checked / visible layers will now also get checked and set to visible. The expanded state of a node needs to be propagated to get used in the treepanel again to correctly show the state of the gizmo treepanel.

Folders visible and expanded state

---

src/util/ConfigParser.js

This PR reenables the crossOrigin attribute on ol.layer.sources.
This has been commented out for no reason, now it gets set dependent on the layer config.

reenable cross origin

---

src/util/ConfigParser.js

PR adds an ol.tilegrid to tiled layers, based on the maps extent and the given resolutions from appcontext. This is needed to avoid some kind of "shrinking" behaviour of tiles on certain zoom levels.

added tilegrid to tiled layers

---

src/util/ConfigParser.js

Since 71e66d5ee6ef7bd70f94538f998ff3df3fb3eeba we overwrite a layers `tileGrid` configuration without checking if …
1. … such a `tileGrid` was already defined in the configuration
2. … the needed inputs for the generation are defined in the `mapConfig`
For 1. we should respect what we were given, and for 2. we should check if the key `resolutions` exists in `appContext.mapConfig`.
Additionally we should really be logging that something unexpected happened in the method `convertStringToNumericArray` instead of silently returning the input.
This is a follow-up for PR #62.

Be more cautious when creating a tilegrid

---

src/view/container/Redlining.js

Usually, the redline vector layer should be hidden, so we set the specific property on instanciaton.
The treestore still needs the filter respecting this property for the filtering to work

Hiding the redline vector layer in the layertree

---

src/util/ConfigParser.js

This PR fixes the order of layerfolders that are contained in a parent folder. This is only relevant when using an application with SHOGun1 appcontext. Its the missing piece of this already merged PR:
https://github.com/terrestris/BasiGX/pull/52

Fixing the order of sub-layer-folders

---

ci/create-sencha-package.sh
package.json

This is an attempt to fix #77, and also a little shot in the dark. I basically want to see if package building still succeeds and whether (after a merge of this PR) clients can again do `sencha package get BasiGX`.

Require package 'ext-ux-colorpick', not the generic 'ux' package

---

package.json

This reverts commit fecd6bc8a2c52db57868affc03658a59ec283738.
See also https://github.com/terrestris/BasiGX/issues/77#issuecomment-210328041 with the above commit things got worse :cry::
```
$ sencha package get BasiGX
Sencha Cmd v6.1.1.76
[INF] Getting package GeoExt/3.0.0
[INF] Package is already local: GeoExt/3.0.0
[INF] Got package GeoExt/3.0.0
[INF] Getting package ext-ux-colorpick/1.0.0.180
[ERR] Error downloading http://terrestris.github.io/BasiGX/cmd/pkgs/ext-ux-colorpick/1.0.0.180/ext-ux-colorpick.pkg
```
I think it's best to first revert the offending commit which changed the depency to `ext-ux-colorpick` and then look further into this.

Revert "Require 'ext-ux-colorpick', instead of generic 'ux'"

---

src/view/panel/GraphicPool.js
src/view/view/GraphicPool.js

Removed invalid bindings for `buttonText` and `emptyText` as these have no setter methods

Fixed bindings for properties that have no setter method

---

src/ux/RowExpanderWithComponents.js

This fixes a bug that removes items mistakenly.
This part of code searches for an item that is added twice. And removes it before. The selection of the item wasn't specfic enough so to many items where removed. Now the items is selected more specifcly.

BugFix for LegendTree-RowExpander

---

src/ux/RowExpanderWithComponents.js
src/view/panel/LegendTree.js

We previously had a method `expandAllBodies`, that would throw an exception
when being called (it called an not-existing method). It also wouldn't expand
all bodies, but merely toggle all of them.
This PR adds the following methods:
* `collapseAllBodies()`,
* `expandAllBodies()`,
* `toggleAllBodies()`.
Please review.
/cc @KaiVolland

Add methods to collapse/expand/toggle legends

---

src/util/Animate.js
src/util/Application.js
src/util/Layer.js
src/util/Map.js
src/view/button/Hsi.js
src/view/button/Measure.js
src/view/button/ToggleLegend.js
src/view/button/ZoomIn.js
src/view/button/ZoomOut.js
src/view/button/ZoomToExtent.js
src/view/combo/ScaleCombo.js
src/view/component/Map.js
src/view/container/LayerSlider.js
src/view/container/NominatimSearch.js
src/view/container/OverpassSearch.js
src/view/container/Redlining.js
src/view/container/WfsSearch.js
src/view/form/AddWms.js
src/view/form/CoordinateTransform.js
src/view/form/Print.js

With this PR some additional config properties  will be introduced to determine map component dynamically and get rid of hardcoded queries like `Ext.ComponentQuery.query('basigx-component-map')[0]`
This change is neccessary to be able to use `mapComponentConfig` object, if we like to use our own `xtype` of map component in the application.
S. here for example:
https://github.com/terrestris/BasiGX/blob/master/src/view/panel/MapContainer.js#L74.
These additional configs can be provided by instantiation of the corresponding `BasiGX` class in the application. Here example for `BasiGX.view.button.ZoomIn` class:
```js
{
xtype: 'basigx-button-zoomin', 
scale: 'small',
olMap: olMap,
ui: 'default'
}
```

Use additional configs to determine map component dynamically

---

src/view/button/AddWms.js
src/view/button/CoordinateTransform.js
src/view/button/Help.js
src/view/button/Hsi.js
src/view/button/Permalink.js
src/view/button/ToggleLegend.js
src/view/button/ZoomIn.js
src/view/button/ZoomOut.js
src/view/button/ZoomToExtent.js

This PR contains a change that has been removed by accident in a previous commit.
We still need to check if the `setTooltip` function is available before we bind the value, as in fact a tooltip for a button does not exist in the modern toolkit.

Fixed buttons to be mobile compatible again

---

src/view/panel/MapContainer.js

In ol 3.17.0 the source MapQuest was removed. See https://github.com/openlayers/ol3/releases/tag/v3.17.0 . So it would be better to use a different source in the overviewmap.

replaces MapQuest layer source

---

src/view/panel/MapContainer.js

In an application I observed that the `layer` from `getOlLayer` might be `undefined` (I issued an unlikely but allowed `removeAll` on the store of the layer tree). 
We should guard against this when adding a filter to our legend panel.
Please review.

Be more cautious when addding a filter

---

src/view/panel/LegendTree.js

This way the plugin instance can be retrieved with code like
```js
legendTree.getPlugin('rowexpanderwithcomponents');
```
Previously there was no way except for iterating over the return value
of `legendTree.getPlugins()`.

Give the rowexpander plugin a pluginId

---

src/view/container/NominatimSearch.js
src/view/container/OverpassSearch.js
src/view/container/WfsSearch.js

These changes are needed due to the removal of the gx_symbolizercolumn in GeoExt3

Removed gx_symbolizercolumn due to removal in GeoExt3

---

src/view/panel/MobileWindow.js

Reserved parameter `title` had to be changed as in ExtJS 6.0.1 this has some strange effect: even if not documented, title will display some kind of broken titlebar.
The `headerPanel` with the close button will now always stay on top if the children get scrolled

Fixed the mobile window

---

src/view/panel/MobileWindow.js

This minor styling change seems to be necessary in ExtJS 6.0.1 when doing a modern production build, as the headerpanel has a transparent background. As this is just a minor styling fix, i will merge this once travis is green

Fixed mobilewindow appearance in production build

---

src/util/Color.js
src/view/container/RedlineStyler.js

In this PR you'll find:
* A new method `rgbaToHex8()` to convert a RGBA color string into an hex8 color string.
* A default (and empty) `ol.Style.Text` object in any redlining style.

Style enhancements

---

src/view/button/Measure.js

`BasiGX.util.Layer.KEY_DISPLAY_IN_LAYERSWITCHER` flag should be set on the layer **before** this will be added to the map, otherwise the `measurelayer` appears in the layerTree.
Please review @terrestris/owners

set filter flag for legend store before layer was added to the map

---

src/util/ConfigParser.js

This mini change is important for print functionality among other things - non transparent layers will be covered by each other so only the topmost layer can be printed.

Set fallback value for layer transparency property to `true`

---

src/util/Animate.js

This PR updates the animate util as it uses the ol3 methods on the vector context which changed in v3.15.0 (https://github.com/openlayers/ol3/releases/tag/v3.15.0).
It can be still used with older versions.

Update animate util

---

src/view/combo/Language.js
test/load-tests.js
test/spec/view/combo/Language.test.js

This PR introduces a small fix for right determination of `viewModel` class, if this was provided not as `type` object, but as `String`.
Also some basic tests were added (till now, there were any tests for `BasiGX.view.combo.Language` at all).
This check is very helpful particularly for classes, which have a "real" `viewModel` classes (not inline).
The bug was detected during momo-project development, the proposed fix was successfully tested with all existing affected classes.
Please review @terrestris/owners

I18n viewmodel determination fix

---

package.json

This changes our npm script for testing to pass the following flags:
* `--ignore-resource-errors`, [docs](https://github.com/nathanboktae/mocha-phantomjs-core#ignoreresourceerrors)
* `--local-to-remote-url-access=true`, [docs](http://phantomjs.org/api/command-line.html)
Please review.

Use commandline flags to make the testsuite less fragile

---

package.json
src/ol3/extension/TransformInteraction.js
src/util/Map.js
src/view/form/Print.js

This PR suggests to add the possoibility to drag and resize the print extent dynamically.
We use the excellent `ol.interaction.Transform` from https://github.com/Viglino/ol3-ext for the interactivity of the extent feature.
This is what is in this PR:
* A utility class `BasiGX.ol3.extension.TransformInteraction` that, when required, will set up the interaction class `ol.interaction.Transform` in the global namespace. The code is taken directly from the linked project, and basically has been reformatted. See the file-header for details on changes.
* Two new utilities in `BasiGX.util.Map`: `getResolutionForScale` and `getScaleForResolution`
* Three new configs for `BasiGX.view.form.Print`: `printExtentAlwaysCentered`, `printExtentMovable`, `printExtentScalable`. The default have been chosen …

Allow dragging and resizing of print extent

---

src/view/button/Measure.js

This PR adds a missing viewModel field declaration that is required (as a default value) to show the appropriate text when drawing an angle.

Add missing msg field for angle measurement

---

src/plugin/Hover.js

Here we cover two minor issues regarding the `Hover` plugin:
* Introduce `enableHoverSelection` to control wether to allow click selection of a hovered feature.
* Only remove ol `Overlays` that are controlled by the plugin itself.

Hover plugin minor bugfixes

---

src/view/combo/Language.js

This PR suggest to guard against locale configs that look misconfigured, and effectively allows us to do things like the following:
```js
// in a button controller
Ext.create('Ext.window.Window', {
viewModel: myBtnViewModel, // a real instance of the vm
bind: {
title: '{myWinTitle}' // defined key in btn viewmodel
}
// other win properties
});
```
That particluar window will benefit from changed locales (with resulting changed viewModels for instantiated things) as long as the original button is rendered / instanciated.
Please review.
/cc @annarieger & @dnlkoch

Check locale config before applying

---

src/util/CSRF.js
test/load-tests.js
test/spec/util/CSRF.test.js

This enhances the CSRF utility to provide two new methods:
* `getParamName` return the name of the CSRF parameter (provided the expected DOM structure exists)
* `getDomHelperField` returns a spec ready to be used with e.g. `Ext.dom.Helper` wjhich will result in an `<input type="hidden"> including the relvant CSRF information.
Please review.

Make the CSRF parameter name also accessible

---

src/view/button/AddWms.js

This makes the "Add WMS" window (optionally) configurable by passing values for the window in the `windowConfig` object that is introduced in this PR.
Existing applications do not need any adaptions (i.e. this code should work fine for them, too).

Make the add wms window configurable

---

src/plugin/Hover.js

Ensure the layer is set as reference to the hover feature before applying the highlight style function.

Fix hover plugin

---

src/view/panel/LayerSetChooser.js
src/view/view/LayerSet.js

This introduces the possibilty to configure a ``BasiGX.view.panel.LayerSetChooser`` by a local config JSON-object, which is passed and interpreted to the underlying ``BasiGX.view.view.LayerSet``.

Make LayerSetChooser configurable with local config JSON

---

src/util/Accessibility.js
src/view/combo/Language.js
test/load-tests.js
test/spec/util/Accessibility.test.js
test/spec/view/combo/Language.test.js

This PR suggests to add a utilty class to enhance the accessibility.
As first step, the method `setHtmlLanguage` is added to set the `lang` attribute of the `<html>`-element, which is usefull e.g. for screenreaders.
Additionally the language combo is changed to call the `setHtmlLanguage` method whenever we know the language of the application or when it has changed.
When reviewing, please only consider ad26d0193cb6da3506ef28256434825b2eb32369 and 171cf19bda7a7669f5b06cf6b3ff75c3e8968e4c, the other commits (188eddf, 9639fd6 and 817d17c) will disappear here once  #135 is merged.
Please review.

Add and use a utility class to enhance accessibility

---

src/plugin/AccessibleTitle.js
src/view/panel/Accessible.js
src/view/window/Accessible.js
test/load-tests.js
test/spec/plugin/AccessibleTitle.test.js
test/spec/view/panel/Accessible.test.js
test/spec/view/window/Accessible.test.js

This adds three components that will enhance the accessibility of apps created using them:
* A plugin to add the title of a component as hidden header (e.g. in a `<h2>`-tag): `BasiGX.plugin.AccessibleTitle`
* That plugin will either render to the `header` or the `body` element of its target
* The plugin also overides the `setTitle` method to update the hidden HTML accordingly when the title changes.
* Two base classes that use this plugin:
* `BasiGX.view.panel.Accessible`: will render their `title` into a `<h3>`
* `BasiGX.view.window.Accessible`: will render their `title` into a `<h2>`
* Both the panel and the window class do this even when configured with `header: false`
* A follow up PR might make the panel- class the base class for all our BasiGX panels
Please review.

Add the ability to add markup to enhance accessibility

---

examples/i18n/resources/locale/app-locale-de.json
examples/i18n/resources/locale/app-locale-en.json
src/view/form/Print.js

Minor layout fixes for print form:
* use `buttons` property instead of `bbar` to harmonize CSS outline with other BasiGX components
* use `anchor` layout for fieldset to fix missed/non uniform padding
* added some labels to enhance usability
Please review @terrestris/owners

Print form layout fixes/enhancements

---

src/view/button/AddWms.js
src/view/button/Base.js
src/view/button/CoordinateTransform.js
src/view/button/Help.js
src/view/button/Hsi.js
src/view/button/Measure.js
src/view/button/Permalink.js
src/view/button/ToggleLegend.js
src/view/button/ZoomIn.js
src/view/button/ZoomOut.js
src/view/button/ZoomToExtent.js
test/index.html
test/load-tests.js
test/spec/view/button/AddWms.test.js
test/spec/view/button/Base.test.js
test/spec/view/button/CoordinateTransform.test.js
test/spec/view/button/Help.test.js
test/spec/view/button/Hsi.test.js
test/spec/view/button/LayerSetChooser.test.js
test/spec/view/button/Measure.test.js
test/spec/view/button/Permalink.test.js
test/spec/view/button/ToggleLegend.test.js
test/spec/view/button/ZoomIn.test.js
test/spec/view/button/ZoomOut.test.js
test/spec/view/button/ZoomToExtent.test.js

This PR suggests to add a common base class for the buttons which allows us to stop copy and paste the constructor part where we have special logic wrt to `setTooltip`.
@annarieger likes it already :smile: but I'd like to as @dnlkoch to look into this as well (in the project he currently working on…)

Add and use a button base class

---

test/.eslintrc
test/spec/plugin/Hover.test.js
test/spec/plugin/WfsCluster.test.js
test/spec/util/Animate.test.js
test/spec/util/Application.test.js
test/spec/util/ConfigParser.test.js
test/spec/util/Layer.test.js
test/spec/view/button/Hsi.test.js
test/spec/view/button/Measure.test.js
test/spec/view/combo/ScaleCombo.test.js
test/spec/view/container/Redlining.test.js
test/test-helper-functions.js

This PR suggestss to add and use some utility methods to ensure a testable setup exists with an `ol.Map` and an `BasiGX.view.component.Map`. This methdos are added:
* `ensureMapComponentAvailable()` only used internally
* `setupTestDiv()` and `teardownTestDiv()` for creating and destroying of `<div>` elements
* `setupTestObjects()` and `teardownTestObjects()` for creating and destroying of `ol.Map` and an `BasiGX.view.component.Map` instances.
For details see the changes in `test/test-helper-functions.js`.
With this in, our tests become way more readable and also we always properly cleanup after ourselves without all the clutter in each specific test file. I hope that writing tests is now easier and might even make fun.
Also included are minor stylistic changes and a previously commented …

Add and use a utility for map/mapComponent setup

---

src/view/list/FocusableTreeItem.js
test/load-tests.js
test/spec/view/list/FocusableTreeItem.test.js

This PR suggests to add a class that can be used inside of `Ext.list.Tree` instances. This tree item class differs to its parent in two points:
* `BasiGX.view.list.FocusableTreeItem` instances can be focused; by clicking or by hitting the tab-key.
* If a focused treeitem receives a `keypress`-event that originates from either the space-bar or the the enter-key, the `selectionchange` event of the parent `Ext.list.Tree` is fired with the focused item passed as new selection.
Please review.

Add a focusable tree item class

---

src/plugin/Hover.js

This adds a zIndex to the Hoverlayer as it should be always on top.

Add zIndex to HoverLayer

---

src/view/panel/MapContainer.js

This adds an event when the overviewmap is toggled. This helps to react to changes it the overviewmaps visibility.

Add overviewmapToggle event

---

examples/i18n/i18n.js
examples/i18n/index.html
examples/i18n/resources/locale/app-locale-de.json
examples/i18n/resources/locale/app-locale-en.json
src/view/form/AddWms.js

This PR suggests some changes to the `AddWms` form:
* Rename the configuration `versionsWmsAutomatically` to `autoDetectVersion`
* Remove configuration `triedVersions`, and instead use an internal property as this should never be set from the user
* Change the `defaultUrl`s default value to be the https-variant
* Add configuration `useDefaultXhrHeader` (to be able to communicate with more actual WMS servers out there, see doc comments for details)
* Add configuration option `disableCaching` (Named as the `Ext.Ajax.request` configuration) to control whether the `_dc`-parameter shall be sent along when fetching the capabilities
* Better error handling:
* OGC `ServiceExceptionReports` are reported with details
* Timeouts  are detected and reported
* Some very common http status codes get …

Multiple enhancements of the AddWms form panel

---

src/view/panel/GraphicPool.js

This PR changes 2 things:
1.) Graphic Pool does not get closed anymore on succcesful image deletion
2.) Parsing of response on image deletion when using REST interface wwill not fail anymore as we check for empty responses and statuscode

Fixes on graphicpool

---

sass/src/view/view/GraphicPool.scss
src/view/view/GraphicPool.js

This PR makes the dataview of the graphicpool component 
* scrollable
* correctly aligned from left to right instead of top to bottom

Fixed the dataview layout of GraphicPool

---

src/view/form/Permalink.js

This fixes a timing related bug in the Permalink form.
As the util is required asynchronous it might happen that `BasiGX.util.CopyClipboard` is not loaded when we try to call `BasiGX.util.CopyClipboard.copyToClipboardSupported` to set the hidden property.
This PR introduces a listener driven solution.
Plz review

Fix timinig issue for copy button.

---

src/view/component/Map.js

Added a postprocess step in the map component. If the function
postprocessMap is defined in your overridden/custom ConfigParser, it
will be called once the component is created (via the call to
callParent).
Please review.

Added postprocess step for config parser.

---

src/view/panel/GraphicPool.js

Use `dockedItems` config with `ui:footer` instead of `bbar` to get more harmonic look and feel of buttons docked at the bottom of the component.

Use docked items with footer ui instead of default bbar in GraphicPool panel

---

src/view/form/AddWms.js

When using a GetCapabilities document with a style element that does not provide a LegendURL element, an TypeError was caught.
This PR fixes this.

Fix uncaught TypeError when adding external WMS

---

src/view/form/AddWms.js

When using the AddWms functionality with a service that provides dozens of layers, they are all checked by default and it's very annoying to deselect all layers you dont want to add.
In my eyes, you most likely want to add a small number of layers, so the default should be false, i.e. you will first have to check the layers you want to add to your map.

Do not check all external WMS by default

---

src/util/Url.js

This allows the detection of word characters (a-z, A-Z, 0-9, underscore) in the extraction of the web project base name out of `window.location.pathname`.

Detect all word characters in the web project base name

---

src/view/button/Measure.js

This introduces tooltip texts to the inline viewmodel.
It also changes the keys for the buttontext to camelcase.
All in all i don't think its a good idea to set the button text in the constructor. But as i think that we rely on this in other projects i'm not going to change this behaviour.
@terrestris/devs Plz review.

Introduces configurable tooltip for measurebutton.

---

.travis.yml

This enables Greenkeeper to also update the `package-lock.json` file. This is exactly the same as e.g. https://github.com/terrestris/node-project-template does it.
Please review.

Enable autoupdate of package-lock.json via GK

---

src/store/GazetteerSearch.js
src/view/component/Map.js
src/view/container/NominatimSearch.js
src/view/panel/MapContainer.js

This changes 4 URLs (twice nominatim and twice the terrestris WMS) to use `https` instead of `http`.
Please review.

Use https where appropriate

---

src/view/form/Print.js

This can be used for custom print requirements such as printing a 'normal' pdf without a map and a given template. It skips the app selection and disables the extent rectangle if the config option `skipMapMode` is set.

Added skip map mode to print w/o extent selection & choosing template

---

src/view/component/Map.js
src/view/grid/FeatureGrid.js

Adds a simple table based on a GeoExt features store. The grid is editable, features are highlighted in the map on mouseover.
As opposed to the feature property grid it displays all features of a layer instead of just one.

Add a basic feature grid

---

src/view/grid/FeatureGrid.js

Added config option for feature grid to ignore columns (defaulting to ['id']).

Ignore attributes

---

src/view/grid/FeatureGrid.js

If starting out with an empty layer, use the first added feature to
determine the attribute schema.
@weskamm please review

Fix empty grid

---

src/view/grid/FeatureGrid.js

This allows to select/deselect features in the grid if they are
added/removed to/from the selection layer's source, also the other way round.

Added selectionLayer config

---

src/util/Demonstration.js
src/util/SldOpenlayersConverter.js
src/ux/ContextSensitiveHelp.js
src/view/button/DigitizeLine.js
src/view/button/DigitizePoint.js
src/view/button/DigitizePolygon.js
src/view/container/Redlining.js
src/view/grid/FeatureGrid.js
src/view/grid/GazetteerGrid.js
test/spec/view/button/DigitizeLine.test.js
test/spec/view/button/DigitizePoint.test.js
test/spec/view/button/DigitizePolygon.test.js

This factores out the digitizing buttons (line, point, polygon) from the redlining component. The buttons can be used seperately and standalone with either a layer or a ol.Collection as a configuration option.
This PR also includes linting fixes (atom only sees the correct .eslintrc if you open BasiGX as a separate project).

Factor out digitize buttons

---

src/view/combo/ScaleCombo.js
test/index.html
test/spec/view/combo/ScaleCombo.test.js

This includes:
* Remove unneeded quotes around object keys
* Turn inline anonymous functions into class methods
* adding and using variables for often used expressions
* Properly unregistering of listeners on OpenLayers objects when the scale combo is destroyed 
* Not updating the scale combo while we are animating, but at the end of the animation as soon as possible (`Ext.Function.createBuffered`)
Please review.

Fix several scale combo issues

---

src/util/SLD.js
src/view/container/SLDStyler.js

This possibly (!) fixes some problems that occured when using the SLD styler classes (but may also introduce a bug in other projects that use the SLD styler when their code is not adapted!?)
`DEFAULT_STROKE_WIDTH` should have a default of `1` in my eyes as this is the default the GeoServer uses. Unfortunately there is some strange magic happening on the GeoServer side when updating a style with such a default value: GeoServer seems to remove default values like `<sld:CssParameter name="stroke-width">1</sld:CssParameter>` from the SLD. The next time the style is loaded in the SLD styler, the value from DEFAULT_STROKE_WIDTH would be used, which was wrong before this PR...
This also adds some defaults to the stroke width numberfield to support decimals.
Furthermore some conditional checks in …

Fix value checks in the context of the SLD styler

---

src/view/grid/FeatureGrid.js

This resolves the issue that identical features, that are already contained in the selectionlayer, will get added multiple times

Fix the highlighting in FeatureGrid

---

test/spec/view/button/SpatialOperatorDifference.test.js
test/spec/view/button/SpatialOperatorIntersect.test.js
test/spec/view/button/SpatialOperatorUnion.test.js

This fixes latest added tests which invoke an `Ext.window.MessageBox`.
While tests will run in browser without this, tests with mocha-phantomjs will fail ..

Fixup tests

---

src/util/Digitize.js
src/view/button/DigitizeDeleteObject.js

Due to the checking for equal geometries many of the digitizing tools run into problems. This is an attempt to fix it.
* if both the clone and the original have an id set, it is used for comparison (thus ruling out false positives)

WIP: Fix feature equality check

---

src/util/ConfigParser.js

`parent` was meant to be `group` in this case

Fixed undefined variable in configparser

---

.eslintrc
src/util/Download.js

Adds a download util to download vector layers as .shp or .geojson clientside only.

Added download util

---

src/ol3/extension/TransformInteraction.js
src/view/form/Print.js

This enables the print extent to be rotatable and modifies the print request to correctly handle rotation

Enable rotation in printform

---

src/view/container/SLDStyler.js

The URL is then used when the SLD is created. That makes it possible for GeoServer to directly communicate with the backend when accessing images (useful eg. in docker environments with an internal network).

Added possibility to configure internal url in sldstyler

---

src/view/button/DigitizeMoveObject.js

Previously the moved feature would be updated even during dragging, possibly resulting in moving a different feature.

Fix changing features when moving

---

src/view/button/ZoomToExtent.js

This adds a config option `extent` to `BasiGX.view.button.ZoomToExtent`, so it can directly be zoomed to a map extent instead of a center and zoom.
Fixes a long standing `TODO` in the API Docs.
Credits go also to @marcjansen :1st_place_medal:

Add config option 'extent' to ZoomToExtentButton

---

src/view/panel/LegendTree.js

The syntax looks quite odd to me anyhow.
Please review.

Remove warning from sencha cmd wrt unescaped backslash

---

Readme.md

If you add `BasiGX` to your ExtJS application you need to add the `ux` package to your application as well. This adds the corresponding configuration snippet to the Readme file.

Document adding 'ux' as require for BasiGX setup

---

src/view/form/Print.js

Adds error handling if GeoExt could not load the capabilities for a template.
@KaiVolland @weskamm Please review.
Needs https://github.com/geoext/geoext3/pull/442 in order to work.

Add print provider error handling

---

src/util/WFS.js

When converting CQL to OGC filter encoding filters one runs into problems when converting string literals (which need to be quoted in CQL but will not match if the quotes are included in the filter encoding variant). With this PR the util will always remove trailing and leading single quotes from all values.

Always replace surrounding quotes when converting cql filters

---

src/util/WFS.js

`viewParams` are only evaluated for `GetFeature` POST requests when embedded in the POST XML, so this PR adds support for it in the WFS util.

Allow viewparams when sending GetFeature POST requests

---

src/view/button/MergeSelection.js

Previously the merge button would fail if not embedded in a `window`.

Support embedding of feature grid functionality in a panel

---

src/util/Merge.js
src/view/button/MergeSelection.js
src/view/window/MergeWindow.js

Also sets an ID on cloned/merged features, else selection will not function properly on the grid nor in the map. Also adds a new config option `mergedFeaturesFn` to get notified once merge has commenced.

Support multiple merge target layers

---

.eslintrc
src/view/MapLoadingStatusBar.js
test/load-tests.js
test/spec/view/MapLoadingStatusBar.test.js

This adds a progressbar which will update itself as soon as sources of a map start / end loading. This brings support for basically all sources, vector sources in applications need to fire approriate events when they load their data. The API docs contain more info on this.
Please review.

Add a MapLoading progress component

---

src/view/button/History.js

This adds a simple history navigation button in order to interact with the HTML5 History API.
Since the History API is supported by current browsers down to IE10 the usage of this might need a polyfill (like https://github.com/browserstate/history.js/) in older browsers, see  https://caniuse.com/#search=history for details.
@terrestris/devs how do you deal with that?

Add a history navigation button

---

src/util/WFS.js

This PR adds a further parameter to `getTimeFilterParts` function in WFS util to pass a time parameter name whioch is not set in layer source.
Plz review @hwbllmnn @weskamm

Allow a fallback for timeParam

---

package-lock.json
package.json
src/view/combo/ScaleCombo.js

Updates mocha to the latest version. Also fixes a test which destroyed the `ScaleCombo` immediately after creating it. In case the tests run fast enough, this will fail since the combo will be destroyed before being fully initialized (it uses a delayed function in init).
Closes #326 

Update mocha to the latest version

---

src/view/MapLoadingStatusBar.js

This ensures that we handle the already configurable keys `duration`, `scope` and `fn` of our `waitConf` correctly.
Please review.

Ensure we handle duration, fn and scope correctly

---

src/view/button/DigitizeModifyObject.js

This includes:
* properly set the old text in the window when modifying
* trigger a redraw by explicitly setting the style

Fixes modify postit

---

src/view/button/DigitizePostit.js

This assumes the BasiGX `resources` folder is copied in the `app.json` to the right location with another entry under the `resources` section like this:
```json
{
"path": "lib/BasiGX/resources",
"output": "resources"
},
```

Fixes image location resolving on production builds

---

src/view/button/SpatialOperatorDifference.js
src/view/button/SpatialOperatorIntersect.js
src/view/button/SpatialOperatorUnion.js

Typically we will have a `toggleGroup` eg. `draw` making sure only one type of features can be digitized at one time. You'll also often have selection functionality in that same `toggleGroup` to avoid digitizing and selecting at the same time.
OTOH, having the spatial operator buttons in that `toggleGroup` makes no sense, since that will effectively remove the selection before having the chance to do the operation.

Removes togglegroup from spatial operator buttons

---

src/view/button/Base.js
test/spec/view/button/DigitizeCopyObject.test.js
test/spec/view/button/DigitizeDeleteObject.test.js
test/spec/view/button/DigitizeModifyObject.test.js
test/spec/view/button/DigitizeMoveObject.test.js
test/spec/view/button/DigitizeOpenStyler.test.js
test/spec/view/button/DigitizePostit.test.js
test/spec/view/button/History.test.js
test/spec/view/button/MergeSelection.test.js
test/spec/view/button/SpatialOperatorBase.test.js
test/spec/view/component/Map.test.js
test/spec/view/container/LayerSlider.test.js
test/spec/view/list/FocusableTreeItem.test.js

This actually revealed one bug (unchecked setting of `tooltip` viewModel config, which would err out when destroying components). 
Several components would not properly cleanup behind them, so that visual artifacts remained in the karma debug page.
Please review.

Add basic instanciation tests and cleanup during tests

---

src/util/SLD.js

Another bugfix for #385: 
When the SLD had no textSymbolizer the pointSymbolizer was removed instead

Fix a bug when removing textSymbolizer

---

src/util/Download.js

The client side shape download was not working for non-IE browsers.

Fixes client side shape download

---

src/view/grid/FeatureGrid.js

When showing the feature grid, the features may not all have the same properties. With this PR, all feature attributes are considered and added as columns.

Extract attributes from all features

---

package-lock.json
package.json

This PR suggests to update
* `eslint` to `v5.14.1`
* `mocha` to `v6.0.0`
Please review.

Update eslint and mocha dependencies to their latest versions

---

package-lock.json
package.json

This updates the following dependencies
* `karma` from `4.0.0` to `4.0.1`
* `mocha` from `6.0.1` to `6.0.2`
Additionally two security issues were fixed by running `npm audit fix`.
Closes #405 
Closes #407

Update dependencies mocha and karma

---

src/view/button/ZoomIn.js
src/view/button/ZoomOut.js
test/spec/view/button/ZoomIn.test.js
test/spec/view/button/ZoomOut.test.js

Added following options to make zoom buttons config more comfortable:
* `enableZoomInWithBox` / `enableZoomOutWithBox` -> Enables zoom with box without `shift` key
* `enableAnimation` -> Enables animation while zooming
* `dragZoomInteraction` / `dragZoomOutInteraction` -> Custom `ol.interaction.DragZoom` which will be used while zooming with box
* `animationDuration` -> Custom animation duration

Make ZoomIn and ZoomOut buttons more configurable

---

src/plugin/Hover.js

Hallo terrestris,
da die Sortierreihenfolge bei getFeatureInfo() zwischen Geometriedarstellung und HoverInfo differiert, soll ein Layer die Möglichkeit besitzen die Sortierreihenfolge im HoverInfo-Fenster umkehren zu können. Dann stimmt die Reihenfolge im HoverInfo-Fenster mit der "Render-Reihenfolge" der Features überein.
Wäre super wenn Ihr die Änderung in die BasiGX übernehmen könntet.
Viele Grüße
Marco Pochert

added hover revert feature order

---

src/util/Date.js
src/util/Filter.js
src/util/GeometryOperations.js
src/util/Jsonix.js
src/util/MouseCoordinates.js
src/util/Namespace.js
src/util/OlStyle.js
src/util/SLD.js
src/util/SldOpenlayersConverter.js
src/util/WFS.js
src/util/WPS.js
test/spec/util/Date.test.js
test/spec/util/GeometryOperations.test.js
test/spec/util/Jsonix.test.js
test/spec/util/MouseCoordinates.test.js
test/spec/util/Namespace.test.js
test/spec/util/OlStyle.test.js
test/spec/util/SLD.test.js
test/spec/util/WPS.test.js

Together with @weskamm i migrated some utils from projects to BasiGX.
Major changes are only in 9c4905e23db2c4efd698798c98b0be01d366d325 so it makes sense to have a sharper look here.
All other utils are new and did not lead to changes in existing classes.

Introduce some utils

---

src/util/Jsonix.js

This PR suggests to only call `new Jsonix.Context(…)` when all globals could be found on the page.
Please review.

Don't try to instantiate a non-existing global

---

src/view/button/ZoomOut.js

This fixes the `zoomOut` button behavior to ensure that `click` listener on the map turns unregistered if button was untoggled.

Add missed scope on map click listener

---

src/util/WFS.js

Adjustments to WFS utils, in particular for determining the `namespaceUri` dynamically in `executeWfsGetFeature`

Adjustments to the WFS utils

---

src/view/button/ZoomIn.js
src/view/button/ZoomOut.js

This fixes a bunch of smaller issues and one bug in the `ZoomIn` and `ZoomOut` buttons:
* The `documentation` entries got some additional markup so that at least they look like a list even though they aren't one
* In the API docs for some configs some sentences were reworded, so that new lines in `/** */` would not start with `#`; that leads to rendering issues once the documentation is rendered with JSDuck (the picture below shows the current rendering before the changes in this PR)
* One typo in inline docs is removed
* bugfix: A hardcoded animation duration of 500 ms is removed and instead the already existing user configurable value is used.
Please review.

Use configured animation duration and fix several other minors in zoom buttons

---

src/util/Object.js
test/spec/util/Object.test.js

It sometimes is desirable to get values from objects where the actual spelling of the key is unclear, e.g. when we write stuff like…
```js
var params = wmsSource.getParams();
var layer = params.LAYERS // will miss params.layers and any other spelling
```
Since the above reflects user-passed values and they are accepted and vald in basically any casing, but at the same time several spelling are more common than others, this PR adds a new method to do just this.
```js
var params = wmsSource.getParams();
var layers = BasiGX.util.Object.getValueSpellingVariants(
params, ['LAYERS', 'layers'], /^layers$/i
);
// layers now contains the value of e.g. params.LAYERS,
// params.layers or params.LaYeRs, whatever we find first
```
Since getting the layers param is quite often requested, this also adds …

Get values for keys with unclear spelling in objects

---

src/util/Layer.js
src/util/Object.js
src/util/WFS.js
test/spec/util/Layer.test.js

This PR suggests to use `BasiGX.util.Object.layersFromParams` from #439 in two classes:
* `BasiGX.util.WFS` (where this was [first noticed](https://github.com/terrestris/BasiGX/pull/438#discussion_r280983349))
* `BasiGX.util.Layer`
The method `BasiGX.util.Layer.getLayerByLayersParam`was also changed to find not only layers with a source `ol.source.TileWMS`, but als those with a source of `ol.source.ImageWMS`. As that partical method also didn't have any tests, I added some as well.
Please review.

Use layersFromParams utility method

---

src/util/Geometry.js
src/util/Namespace.js

Fixes the namespace/wfs utils backwards compatibility. Also addresses comments from #446 .

Fix namespace util backwards compatibility

---

src/util/WFS.js
test/spec/util/WFS.test.js

This changes the WFS util so it can be used to work with filters
that either have or don't have the `ogc:` namespace prefix.
The methods `unwrapFilter` and `getFilterPrefix` both will be
positively affected by this change.
Please review.

More flexible regular expression to work w/ filters

---

src/plugin/Hover.js

The positioning calculation for the `ol.overlay` of the hover plugin was wrong when the innerHtml contained divs.
`'table-cell'` is used as display-mode for the wrapping div to ignore child divs, which may transform the wrapper.

Fixes calculation for hover overlay positioning

---

src/util/MsgBox.js

This sets the default for the buttons to show to `Ext.MessageBox.OK` as it's normally not needed to distinguish between `OK` and `Cancel` for warn messages.

Only show the OK button for warn message boxes

---

src/view/button/CSW.js
src/view/form/CSW.js
test/resources/ows/csw-response.xml
test/spec/view/form/CSW.test.js

This is currently restricted to WMS services only, but should be easily extendible to support WFS.
I tried hard to parse the CSW responses with Jsonix, but i failed and decided to use the DOMParser for this trivial task.
All it does is to request the given csw endpoint with `GetRecords`. It collects all records that have a dc:URI with an OGC:WMS protocol and generates buttons for that.
When clicking a button, the well known `BasiGX.view.form.AddWms` is used to retrieve the layer by automatically issuing a GetCapabilities request against the URL.

Add a CSW form to retrieve WMS layers through CSW

---

src/view/form/CSW.js

This ensures that the CSW search is executed if the ENTER key is hit inside the search text field of the `BasiGX.view.form.CSW`.

Execute CSW search on ENTER in search text field

---

src/util/WFS.js

If `featureType` is passed as parameter, its determination from `PARAMS` is omitted.

Wfs util: use passed feature type if provided

---

src/view/MapLoadingStatusBar.js

This ensures Vector Tile layers are also taken into account for the loading status in the `MapLoadingStatusBar`. Therefore all sources inheriting from `ol.source.Tile` (not only `ol.source.TileImage`) will be checked.

Support Vector Tile layers in MapLoadingStatusBar

---

src/view/button/Base.js

This removes the constructor and adds binding for `text` and `tooltip` for the `BasiGX.view.button.Base`.

Fixes tooltip binding in base button

---

src/view/button/AddWms.js
src/view/button/CoordinateTransform.js
test/spec/view/button/AddWms.test.js
test/spec/view/button/CoordinateTransform.test.js

Previously `AddWms` and `CoordinateTransform` windows could be shown only once. 
After the component was called repeatedly (e.g. after the window was closed), the console error was thrown, cause the window instance was not reset properly:

Reset window reference on destroying properly

---

src/util/WPS.js

Herewith, vector processes having WFS get feature inputs can be used, e.g.
```<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute version="1.0.0" service="WPS"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.opengis.net/wps/1.0.0"
xmlns:wfs="http://www.opengis.net/wfs"
xmlns:wps="http://www.opengis.net/wps/1.0.0"
xmlns:ows="http://www.opengis.net/ows/1.1"
xmlns:gml="http://www.opengis.net/gml"
xmlns:ogc="http://www.opengis.net/ogc"
xmlns:wcs="http://www.opengis.net/wcs/1.1.1"
xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
<ows:Identifier>vec:Nearest</ows:Identifier>
<wps:DataInputs>
<wps:Input>
<ows:Identifier>features</ows:Identifier> …
```

WPSUtil: Introduce WFSGetFeature as input reference

---

src/util/WPS.js

This PR affects the `WPSUtil`: If GetFeature is used as referenced datatype and `maxFeature` is not set its occurrence in request string must be removed.

Replace maxFeatures string by an empty one if maxFeatures is not defined

---

src/view/panel/CoordinateMousePositionPanel.js

If a map is available use its initial centre point to fill text boxes. If a user sets X,Y on the model these will take precedent. See #521. 
A couple of questions:
- should this be made an option so it can be enabled/disabled?
- there doesn't seem to be a way to set the starting projection for CoordinateMousePositionPanel (it is always the map projection?), so the centroid takes the map projection.

Initialize coords to map's starting center

---

src/plugin/Hover.js

Previously multiple clones of same feature were shown while hovering over any vector layer and default feature style (blue point with transparent fill for points etc.) was always used for highlighing.
This PR provides the following fixes: 
* Enhance check for hover feature candidates and prevent adding of dublicated features
* Set highlighing style on hovered features properly

Enhance hovering of vector layer features

---

src/plugin/Hover.js
test/spec/plugin/Hover.test.js

Adds possibility to set custom color while hovering over features.
The default behaviour (red color with 0.6 opacity) is unchanged.

Make hoverColor property of hover plugin configurable

---

examples/i18n/resources/locale/app-locale-de.json
examples/i18n/resources/locale/app-locale-en.json
src/view/container/MultiSearchSettings.js
src/view/form/field/MultiSearchCombo.js
src/view/grid/MultiSearchGazetteerGrid.js
src/view/grid/MultiSearchWFSSearchGrid.js

* Make use of original `minChars` config of [`Ext.form.field.ComboBox`](https://docs.sencha.com/extjs/6.2.0/classic/Ext.form.field.ComboBox.html#cfg-minChars) to trigger search  only after the certain amount of symbols was typed
* Delay search triggering while typing
* Show "no results found" message if no results for searched term were found
* Mark configuration of "searchable layers" in search settings as disabled if "Object search" option was unchecked
* Add possibility to restrict the max count of features retrieved by WFS search via search settings option "Max search result count"
* Show count of found features in grouped header inside of wfs search grid (previously only layer name was shown)
* Fix (un)registering of mouse hover and click events on search result grids
* Hide search …

Diverse enhancements of Multisearch component

---

src/plugin/Hover.js
src/util/StringTemplate.js
src/view/grid/MultiSearchWFSSearchGrid.js
test/spec/util/StringTemplate.test.js

Previously only `PropertyIsLike`  filter was implemented so only string based attributes could be searched through via WFS. 
This MR extends `MutiSearchWFSSearchGrid` class and adds possibility to query numeric attributes (`xsd:number` or `xsd:int`) as well.
To achieve this, an additional filter function `stringFormat` was implemented.
Please note, that numeric attributes can be only be queried and filtered, if an additional extension [`terrestris-filterfunctions-0.0.1.jar`](https://nexus.terrestris.de/repository/public/de/terrestris/terrestris-filterfunctions/0.0.1/terrestris-filterfunctions-0.0.1.jar) is available in geoserver. Please refer to https://github.com/terrestris/terrestris-filterfunctions for further details. 
If layer is configured with custom property `searchable` and has a …

Make use of custom layer search configuration with WFS search

---

src/plugin/Hover.js

In addition to https://github.com/terrestris/BasiGX/pull/527 this change fixes some strange behaviour when hovering over vector layers.
First time hovering over a vector was fine, but every subsequent hover action on the same feature resulted in a growing layer (and also feature) list in the popup. The problem also occured at locations where two or more features had the same (or at least similar) geometry.
To avoid the growing layer list, there is a simple check whether the layer is already contained in the `hoverLayers` array.
To avoid the growing feature (template/attribute) list of a layer, the (maybe generated) `id` of `feat` is also applied to its clone to be able to check whether this feature should be added in the next iteration or not.

Handle hovering over vector layers correctly

---

src/view/form/field/MultiSearchCombo.js
src/view/grid/MultiSearchWFSSearchGrid.js

Followup of https://github.com/terrestris/BasiGX/pull/548
Introduced an additional config `useGeoServerStringExtension` (default to `false`) to decide, whether the custom geoserver filter extension should be used for attributes filter while querying of numeric attributes.
if not, `strTrim` geoserver filter [string function](https://docs.geoserver.org/stable/en/user/filter/function_reference.html#string-functions) will be used as fallback.

Add check for geoserver filter extension used with WFS search

---

src/plugin/Hover.js
src/view/form/AddWms.js

Extracts the layer extent when adding a WMS layer and stores it on the source as `layerExtent`.

Extract the layer extent

---

src/view/form/field/MultiSearchCombo.js
src/view/grid/MultiSearchWFSSearchGrid.js

Previously the search result container could be only removed if the search field was cleared.
Added a trigger which allows to hide and show results again.
Also added 2 further configs to `MultiSearchWFSSearchGrid` component:
* `zoomToSearchResults` - whether the map should zoom to clicked search result, default is false (old behaviour)
* `zoomToScale` - optional config which defines scale value, which should be used as max zoom by click on search result if `zoomToSearchResults` option is set to true.

Add close trigger to `MultiSearchCombo` component

---

src/view/form/AddWms.js

This adds a config option to specify a proxy URL which will be applied to the capabilites requests.
Useful e.g. when having issues with CORS

Add proxy URL config to add wms form

---

src/ol3/extension/TransformInteraction.js

For unknown reasons the call to `ol.interaction.Pointer` suddenly caused an access of the overlay layer before it was initialized. This fixes the initialization order so the overlay layer is initialized first.

Fix order of initialization

---

src/view/grid/MultiSearchWFSSearchGrid.js

* Pass featuretype namespace detected from `DescribeFeatureType` request to attribute filter
* Use spatial filter if only spatial restriction checkbox is set in search settings
* Enhance determination of search layers by using of original featuretype name instead of possibly customized layer name
* Enhance error handling on failed parsing of `DescribeFeatureType` response

Enhance ftname detection

---

src/view/panel/CoordinateMousePositionPanel.js

This introduces the config property `activeEpsgCode` for the `BasiGX.view.panel.CoordinateMousePositionPanel` class in order to configure the initially selected EPSG code. Before the last element in the list was set as active EPSG code, which is still the fallback in case `activeEpsgCode` is not provided.

Introduce 'activeEpsgCode' for 'CoordinateMousePositionPanel'

---

src/view/form/AddWms.js

According to the WMS spec all CRS in the layer's hierarchy are inherited. With this PR this is considered when checking for a layer's compatibility.
Also sets the 'fetch layers' button as default button.

AddWMS: Use inherited CRS list to check for compatibility

---

src/plugin/HoverClick.js
test/spec/plugin/HoverClick.test.js

This introduces the hoverClick plugin.
This plugin extends the hover plugin to disable/enable click and hover events separately.
To do so, two configs  `hoverable`, `clickable` were added to enable/disable hovering and clicking globally. These values just set the general options to disable/enable hovering and clicking. A layer  needs to have a truthy `hoverable` or `clickable` property to actually enable hovering and clicking respectively.
Now, separate requests for the click and the hover event will be fired.
Please note that it is required to manually cleanup the feature selection (`hoverClickPlugin.cleanupHoverArtifacts()`) after the `hoverfeaturesclick` event was fired, as in contrast to the `pointerrest` event, we cannot know when the cleanup should be triggered.

Introduces hoverClick plugin

---

src/plugin/HoverClick.js

This fixes the firing of the `hoverfeaturesclick` event for the hoverClick plugin. 
Now, the `hoverfeaturesclick` event will be fired in the callback of the newly added separate gfi request for click events. Previously, the `onFeatureClicked` of the parent fired the event, which is not aware of the additional async process.

Fix hoverClick firing of hoverfeaturesclick

---

src/plugin/Hover.js
src/util/Url.js

This enables rendering clickable links in the popup of the `hover` and `hoverClick` plugins.
When setting the config `enableClickableLinks` to `true`, strings that start with `http(s)://` will be rendered as anchors with `target="_blank"`.
To maintain backwards compatibility, the default of the config is set to `false`.

Enable Clickable Links for Hover Plugin

---

src/ux/RowExpanderWithComponents.js
src/view/panel/LegendTree.js

This makes the keybindings of the row expander plugin consistent with standard ext trees.

Fix keybindings of row expander plugin to be consistent

---

src/view/list/FocusableTreeItem.js

This PR adds/removes the `x-focused` class on focusenter/leave and simulates click events when hitting space or enter on focused items.

Fix focusable tree item to allow actual actions

---

src/view/grid/MultiSearchWFSSearchGrid.js

The WFS search grid groups by feature type name by default. This adds an option to instead use the layer name (determined from `layer.get('name');` instead.

Allow use of the layer name instead of feature type for grouping

---

src/util/Layer.js
test/spec/util/Layer.test.js

This adds a util function `BasiGX.util.Layer.cascadeLayers`, which cascades down a given OL LayerGroup and calling the given function for each LayerGroup / Layer.

Add util function BasiGX.util.Layer.cascadeLayers

---

src/view/panel/GraphicPool.js
src/view/view/GraphicPool.js

Pass optional filter function to `GraphicPool` components which can be used to exclude some records from pool.
Use case:
Pool contains images in different formats, but only PNGs should be displayed.
Additionally adds missed vertical scrollbar to view component.
@terrestris/devs

Optional filterFn config for GraphicPool components

---

src/view/grid/MultiSearchWFSSearchGrid.js

- Sets the layer of a found and clicked record to visible
When a layer is set to unvisible in the clients layer-tree and a search result of that layer is clicked, the map zooms to an unvisible feature on the map. This should fix this behaviour.
Please note @terrestris/devs

Multisearch: Show layer on record click

---

src/view/container/MultiSearchSettings.js
src/view/form/field/MultiSearchCombo.js

Fix layout of multisearch settings window:
* Show "Save settings" button docked on bottom
* Add maxHeight and scrollbar to "searchable layers" container to prevent window dimensions exceeding screen size

Fix layout of multisearch settings window

---

src/view/grid/MultiSearchWFSSearchGrid.js

This enables WFS searching on layers that are located in different workspaces.
We have to fire the `describeFeatureTypes` request for each workspace separately, as we otherwise loose the information of the workspace name for the `getFeature` request.

Search across multiple workspaces

---

src/view/form/AddWms.js

This unchecks all layers before removing them if another wms was requested. This ensures that the on change handler on the checkboxes is working as expected.
Fixes https://github.com/compassinformatics/cpsi-mapview/issues/300

uncheck layers before removing

---

src/plugin/HoverClick.js
src/view/button/Hsi.js

Introduce config flag `clickActive` to control, whether the `click` event on the map should be triggered or not.
The config state will be changed on `HsiButton` component toggle.

Prevent click event on HsiButton untoggle

---

src/view/button/Measure.js
test/spec/view/button/Measure.test.js

From https://openlayers.org/en/latest/apidoc/module-ol_sphere.html - `getArea` expects a geometry rather than an array of coordinates. 
Otherwise the following error is thrown: `e.getType is not a function`

Update measure area tool for ol6

---

src/view/form/AddWms.js

This pull request ensures that the "Request available layers" button becomes enabled if a user enters or pastes a URL in the WMS-URL box. 
Currently if the combobox has a list of entries then the texfField is hidden, but it does not allow blank values, so the form is never valid and the button is disabled (a user however could select something from the dropdown and then paste text as a workaround).

Enable button in the addWms form when the textbox is hidden

---

src/view/form/CSW.js

This adds the possibility to configure the `BasiGX.view.form.CSW` component with an optional AJAX proxy URL, which is placed before the "real" target CSW URL.

Add optional AJAX proxy URL config for CswForm

---

src/view/form/AddWms.js

This change adds a horizontal scrollbar so all WMS layers can be seen in the fieldset when layers span multiple columns (image of updated form below):

Allow horizontal scrolling on Add WMS form

---

src/view/grid/FeatureGrid.js

Note: passing `undefined` to the `header` option of the panel is actually restoring backwards compatible behaviour, passing `true` breaks things when ext tries to access the header object in other places and finds no object.

Fix gridHeader config default

---

src/view/button/DigitizeModifyObject.js
src/view/button/DigitizeMoveObject.js
src/view/grid/FeatureGrid.js

Updates the button state of cancel and save button, if data was edited.
Also had to remove `changefeature` listener, as this will also be called when the style of a feature changes. This always happens when moving/modifying a geometry. Therefore, now the `featurechanged` events of the modify/move buttons also pass through the openlayers event.

Change save/edit button state when table or geometry was edited

---

src/view/grid/FeatureGrid.js

This removes the usage of the lockFeature request for WFS-T requests, as this poses quite a few problems when used in GeoServer.
This also make better usage of the viewModel.

Remove usage of lockFeature on FeatureGrid

---

src/view/grid/FeatureGrid.js

Adds a reload button the triggers a `reloadgrid` event to provide means for reloading the data.
This also adds a success toast when saving was successful.

add reload button to feature grid

---

src/view/grid/FeatureGrid.js

This prevents showing the saveReminder after saving changes in the feature grid.
The reminder was triggered by the update event of the store which itself was triggered by our `commitChanges` call when saving the changes.

fix showing saveReminder after saving in feature grid

---

package-lock.json
package.json

Updates np manually to hopefully fix the release. We'll also have to see why dependabot didn't pick up the new `np` version.
@terrestris/devs Please review

chore: update np to 7.6.2

---

src/util/ArcGISRest.js
src/util/Url.js
src/ux/ContextSensitiveHelp.js
src/view/button/AddArcGISRest.js
src/view/form/AddArcGISRest.js
test/spec/util/ArcGISRest.test.js
test/spec/util/Url.test.js
test/spec/view/form/AddArcGISRest.test.js

This introduces the form for adding layers via the ArcGIS Rest API.
Currently, following features/formats are supported:
- import services of type `MapServer`
- import services of type `ImageServer`
- import mentioned services from any ArcGIS Rest folder
Following features are not (yet?) supported:
- import services of type `FeatureServer`
- import single layers of a service
This is basically a copy of `basigx-form-addwms` with adjustments to fit the ArcGIS Rest API. Therefore, the code might benefit from a minor refactoring in a follow-up PR.
In contrast to `basigx-form-addwms`, the OpenLayers layers will only be created when `Ausgewählte Layer hinzufügen` was clicked. This was done to reduce the number of http requests.
Example import from root folder:
Example import from sub folder:

introduces basigx-form-addarcgisrest

---

Readme.md
src/util/ArcGISRest.js
src/view/form/AddArcGISRest.js
test/spec/util/ArcGISRest.test.js

This adds support for ArcGIS REST FeatureServer layers.
Currently, only importing single layers of a FeatureServer are supported. We get the layer information by firing http requests to all services in an arcGIS folder that are of type FeatureServer. We then take the layer definitions from the responses and add them to the list of checkboxes in the UI. When importing, all features of a single layer will be requested and added as unstyled ol.layer.Vector.

Introduce support of arcGIS REST FeatureServer layers

---

src/view/panel/CoordinateMousePositionPanel.js

This adds an optional marker to the map, when the `centerToCoordinate` button was clicked. The marker will be removed with the next map click. By default, the marker uses the default ol style. A custom style can be added via config. Same goes for the layer, where the marker should be added to.
Example with styled marker:

Add option to add marker to coordinatemouseposition

---

src/view/panel/CoordinateMousePositionPanel.js

This removes the error prone click event that was added when placing a coordinate marker on the map.
Since we cannot simply suppress all other map events, the component itself cannot handle the marker click event properly. Therefore, we changed it so that now, the using application has to handle the click event. The using application can thereby harmonize the click events with all other used events.
In order to do so, we now provide eventlisteners for checking if a given feature is the coordinate marker, and for removing that marker.

Remove error prone click event from marker layer

---

src/view/button/CoordinateTransform.js
src/view/form/CoordinateTransform.js

* Use EPSG:4326 as default fallback CRS to enable tool usage without any customization
* Previously tool instantiation was failed if configured without `coordinateSystemsToUse` config
* Enhance form layout
* Add "Copy to clipboard" button
* Fix margins for form elements
* Improve styling of clicked position on the map
*  Use crosshair marker instead of filled red circle

Transform coordinates tool enhancements

---

src/view/form/AddArcGISRest.js

If a server has no FeaureServers then an error is thrown when calling ` Ext.Array.reduce` on an empty array: `TypeError: Reduce of empty array with no initial value`.
This check simply avoids calling the function when `responses` is empty.

Check for empty arrays prior to reduce call in BasiGX.view.form.AddArcGISRest

---

src/view/container/MultiSearchSettings.js

Make some initial settings for multisearch configurable:
- whether to restrict the search to the map extent
- whether to use OSM / Gazetteer search
- whether to use object (layer attribute) search
Default value for all these configs is `true` and complies with existing component behaviour.

Configurable search settings

---

src/view/grid/FeatureGrid.js

Adds the possibility to configure an example feature for the feature grid in case it initially contains no features. It will be used to determine the column titles.

Add example feature config

---

src/view/grid/FeatureGrid.js

* Auto adapt height of the grid on parent element resize to fit all available place
* Get rid of some hardcoded height values, make height of grid toolbar configurable
* Force columns to fit into available grid width (excepting zoom action column, which width is restricted by 35px)

Fix feature grid layout

---

src/model/Projection.js
src/store/Projections.js
src/util/Projection.js
src/view/panel/CoordinateMousePositionPanel.js
test/spec/util/Projection.test.js

In relation to https://github.com/compassinformatics/cpsi-mapview/issues/615
This PR allows consumers of BasiGX to pre-load epsg.io responses to avoid requests to that service.
It uses a singleton store, `BasiGX.store.Projections` to which definitions can be added. When `fetchProj4jCrsDefinitions` is called it will check if the definition exists in the store, if it exists it will use it, if not it will request the definition from epsg.io.
Definitions can be pre-loaded like this:
```javascript
projectionsStore.loadData([{
    id: 'EPSG:4326',
    code: '4326',
    name: 'WGS 84',
    proj4: '+proj=longlat +datum=WGS84 +no_defs +type=crs',
    unit: 'degree (supplier to define representation)',
}, {
    id: 'EPSG:29902',
    code: '29902',
    name: 'TM65 / Irish Grid',
    proj4: …
```

Allow pre-loading projection definitions to avoid requests to epsg.io

---

.github/workflows/on-pull-request.yml
.github/workflows/on-push-master.yml
.github/workflows/on-tag.yml

This fixes failed CI checks like this one: https://github.com/terrestris/BasiGX/actions/runs/4563233373/jobs/8051469360
Compare e.g. https://github.com/geoext/geoext/pull/722
Please review.

Use a maintained GH action to setup ruby

---

src/plugin/Hover.js
src/plugin/HoverClick.js

OpenLayers 7 removed deprecated functions like `forEachLayerAtPixel` (see https://github.com/openlayers/openlayers/releases/)
This change refactors/re-implements the use of this function in BasiGX

Refactor deprecated forEachLayerAtPixel

---

src/view/grid/FeatureGrid.js

Adds a configuration option to configure a zoom padding for the zoom column in the feature grid.
PR for 3.x

feat: add zoom padding

---

src/view/grid/FeatureGrid.js

This adds the maxZoom config that sets the maxZoom on `view.fit()`. This comes in handy when zooming to point data, where it is hard to retrieve a proper extent.

add maxZoom to FeatureGrid

---

src/view/grid/FeatureGrid.js

This allows configuring the visibility of columns for the featuregrid. Please note, that this will still allow users to set columns in-/visible by using the UI.

feat(featuregrid): allow configuring column visibility

---

src/view/form/AddArcGISRest.js

If `response.responseText` contains an error  e.g. `'{"error":{"code":400,"message":"Invalid URL","details":[]}}'` then `res.layers` is undefined causing a JS error `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')` and the form to become stuck. 
This update adds a simple check and returns an empty array to prevent this.

Add check for ArcGISRest service requests returning errors

---

src/view/panel/CoordinateMousePositionPanel.js

The comment states `// Loose equality check since code could be a string or an int` however an exact check is used. 
This then causes `filtered` to be an empty array when checking `3857 ==== "3857" `between a projection code in the store and the projection code from the map. 
Results in the JS error:
```
CoordinateMousePositionPanel.js?_dc=1737122544728:347 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
at constructor.generateCrsChangeButtonGroup (CoordinateMousePositionPanel.js?_dc=1737122544728:347:53)
at CoordinateMousePositionPanel.js?_dc=1737122544728:273:20
```
In addition the `filtered ? filtered[0].name : ''` will return `true` for an empty array (which is always created using Ext.Array.filter)  - updated to account for this.

Check for proj codes as str or int in CoordinateMousePositionPanel
